services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "dkqw091j4ktgjg09we"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  front:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./apps/front/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - back
    ports:
      - "3000:3000"

  back:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - 3001:3001

volumes:
  postgres-data:
