version: "3"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'dkqw091j4ktgjg09we'
    ports:
      - 3333:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
