import { DesignProvider } from "@/components/design-provider";
import { HeaderAuth } from "@/components/header-auth";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="container flex justify-between items-center h-[80px]">
          <Link href="/">Hello World</Link>
          <HeaderAuth />
        </header>
        <main className="container">{children}</main>
        <DesignProvider />
      </body>
    </html>
  );
}
